### ISSUE TITLE
Issue with searching (Cannot comprehend data)

### ISSUE THREAD

**Issue by araripe** [tjol/vinylscrobbler#13]
I've been getting this for a few weeks now, any updates on an upcoming fix? Thanks!

**Comment by MartinL0815** [comment]
Sincerely this bug is back!

Since last week I cannot search discogs anymore!

**Comment by jvanhie** [comment]
This is due to another Discogs API change, from now on all calls are https only, I suppose the redirect from the http call isn't handled properly. See announcement here: https://www.discogs.com/forum/thread/521520689469733cfcfd2089#7033144

**Comment by MartinL0815** [comment]
And?
Even if!
The announcement and change is not that surprising, is it?
And as user, I expect early reactions ensuring the functionality of an app and not a lot of disappointed users!

Any chance for a fix for 0.4+?

**Comment by jvanhie** [comment]
I can't speak for tjol, the developer of the app. I'd expect the needed changes to be acceptable, but it's been years since I had a look at the code itself since I spun off my own Discogs Scrobbler app. It's not on the play store since I didn't feel like paying the developer fee and having my mailbox flooded with bug reports, but if tjol wouldn't pull through I'll probably reconsider. 
In the meanwhile, I've compiled an apk on my github if you want to keep scrobbling those records :-) https://github.com/jvanhie/discogsscrobbler/releases/tag/v1.0

**Comment by tjol** [comment]
Sorry, guys. It's also been ages since I've looked at the code myself. Obviously I don't like to disappoint users, and I'm really glad there are people who enjoy my app (or would if it worked). Still, @MartinL0815, there's no reason to talk like I owe you anything. It's not like I make any money off it, and it _is_ almost five years old (and as you can see, it has barely been updated in that time).

That being said, I'm working on it, and there should be a fix on the Play Store later today. @jvanhie, thanks a lot! I think you're right about the https thing.
